### ISSUE TITLE
How to Make Facebook Status Visible to Certain Persons Only

### ISSUE THREAD

**Issue by eaba** [abjerner/Skybrud.Social.Facebook#15]
Hello,
I want to understand how "Share With" works with your api in particular and to know the limit on the numbers of users that can be added by facebook.

Thanks

**Comment by abjerner** [comment]
@eaba I'm not really sure that I understand your question?

Share With is typically a feature users will do in their own browsers, and as such not something that is supported in the implementation of this package.

**Comment by eaba** [comment]
I want to handle multiple subscription on one facebook bot. So when a subscription post to my page i want only the users registered to a subscription to see the post and not the general public.

Facebook has something like that when select audience, there is an option not to share with certain users.
Is this possible using this api?

How to Make Facebook Status Visible to Certain Persons Only

**Comment by abjerner** [comment]
@eaba As I understand your answer, this is not something that is supported in my implementation.

If you can point to related documentation of the Graph API, I can have a look at it ;)

**Comment by eaba** [comment]
Okay
