### ISSUE TITLE
Facebook Debug token Response.cs

### ISSUE THREAD

**Issue by pccplayer411** [abjerner/Skybrud.Social.Facebook#17]
Is that facebookdebugtokenresponse.cs missing?? when i build i found this error

**Comment by abjerner** [comment]
Unfortunately yes. It is probably because file is located in a folder called `Debug`, which means the files then will be ignored by Git. I will make sure to add the missing files when I get back home ;)

**Comment by abjerner** [comment]
@pccplayer411  I have now committed the missing file ... and pulled down the entire repository again on another location to test that is actually builds ;)
