### ISSUE TITLE
Access facebook reviews

### ISSUE THREAD

**Issue by realtaken** [abjerner/Skybrud.Social.Facebook#21]
Hope you could point me in the right direction to display a page's facebook reviews. Struggling to find anything in the api. Thank you.

**Comment by abjerner** [comment]
API wise, reviews seems to be called ratings - if you wish to play around with ratings directly via the API, there's some more information here:

https://developers.facebook.com/docs/graph-api/reference/page/ratings

Skybrud.Social unfortunately doesn't support this at the moment.
